room_dim:
- 5
- 8
- 3

src_pos:
- 2.5
- 1
- 1.75

mic_pos:
- 2.5
- 2.5
- 1.75

mic_array_grid: [20, 20]  # [rows, cols]

mic_spacing: 0.05  # meters

mic_pos_path: "data/simulated/pos_square_20x20.csv"

rir_path: "data/simulated/rir-simulated.wav"

materials:
  floor:   ["linoleum_on_concrete",    0.1]
  ceiling: ["ceiling_fissured_tile",   0.2]
  north:   ["plasterboard",            0.1]
  south:   ["plasterboard",            0.1]
  east:    ["curtains_densely_woven",  0.5]
  west:    ["plasterboard",            0.1]

ism:
  max_order:    50
  use_rand_ism: false
  max_rand_disp: 0.05

ray_tracing:
  enabled:         true
  n_rays:          10000
  receiver_radius: 0.1
  energy_thres:    1.0e-7

environment:
  fs:           16000
  humidity:     0.0   # %
  air_absorption: false
  sigma2_awgn:  null   # estimated from real RIRs at runtime